version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scrapy
    networks:
      - mynetwork

  web:
    build:
      context: .
      dockerfile: web.dockerfile
    command: bash -c "python scrapy_api/manage.py makemigrations && python scrapy_api/manage.py migrate && python scrapy_api/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=scrapy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SCRAPYD_HOST=scrapyd
    depends_on:
      - db
    networks:
      - mynetwork

  scrapyd:
    build:
      context: .
      dockerfile: scrapy.dockerfile
    ports:
      - "6800:6800"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=scrapy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - mynetwork


networks:
  mynetwork: