# Generated by Django 4.2.2 on 2023-06-26 16:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_app', '0003_rename_product_chemicals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicals',
            name='qt_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None),
        ),
    ]
