# Generated by Django 4.2.2 on 2023-06-29 06:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scrapy_app", "0004_alter_chemicals_qt_list"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chemicals",
            options={"ordering": ["-datetime"]},
        ),
    ]
